name: generic_json_converter_generator
description: A generic json converter generator for json_serializable.
version: 0.0.2
homepage: https://github.com/windrunner414/generic_json_converter_generator

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  analyzer: ">=0.37.1 <0.39.0"
  build: ">=0.12.6 <2.0.0"
  source_gen: ^0.9.0
  generic_json_converter_annotation: ">=0.0.1 <1.0.0"

dev_dependencies:
  build_runner: ^1.0.0
