name: generic_json_converter_annotation
description: A generic json converter generator for json_serializable.
version: 0.0.2
homepage: https://github.com/windrunner414/generic_json_converter_generator

environment:
  sdk: ">=2.1.0 <3.0.0"
